apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../applications/metallb
- ../../../applications/cert-manager
- ../../../applications/ingress-nginx
- ../../../applications/grafana
- ../../../applications/prometheus
- ../../../applications/namespace.yaml
- ../../../applications/helmrepository.yaml
- ../../../applications/logstash
- ../../../applications/kibana
- ../../../applications/elasticsearch