apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../applications/infrastructure/metallb
- ../../../applications/infrastructure/cert-manager
- ../../../applications/infrastructure/nginx-ingress
- ../../../applications/infrastructure/grafana
- ../../../applications/infrastructure/prometheus
- ../../../applications/infrastructure/namespace.yaml
- ../../../applications/infrastructure/helmrepository.yaml
- ../../../applications/infrastructure/logstash
- ../../../applications/infrastructure/kibana
- ../../../applications/infrastructure/elasticsearch