# infrastructure/logging/logstash.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: logstash
  namespace: logging
spec:
  interval: 30m
  chart:
    spec:
      chart: logstash
      version: "8.5.1"
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
  values:
    replicas: 1
    resources:
      requests:
        cpu: "250m"
        memory: "1Gi"
      limits:
        cpu: "500m"
        memory: "1536Mi"
    logstashJavaOpts: "-Xmx512m -Xms512m"
    extraEnvs:
      - name: ELASTICSEARCH_USERNAME
        valueFrom:
          secretKeyRef:
            name: elasticsearch-master-credentials
            key: username
      - name: ELASTICSEARCH_PASSWORD
        valueFrom:
          secretKeyRef:
            name: elasticsearch-master-credentials
            key: password
    # Mount the pipeline ConfigMap
    extraVolumes:
      - name: pipeline-config
        configMap:
          name: logstash-pipeline
      - name: elasticsearch-certs
        secret:
          secretName: elasticsearch-master-certs
    extraVolumeMounts:
      - name: pipeline-config
        mountPath: /usr/share/logstash/pipeline
      - name: elasticsearch-certs
        mountPath: /usr/share/logstash/config/certs
        readOnly: true
    extraPorts:
      - name: http-events
        containerPort: 5044
    service:
      type: ClusterIP
      ports:
        - name: http-events
          port: 5044
          protocol: TCP
          targetPort: 5044