# infrastructure/logging/elasticsearch.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: logging
spec:
  dependsOn:
    - name: ingress-nginx
      namespace: flux-system
  interval: 30m
  chart:
    spec:
      chart: elasticsearch
      version: "8.5.1"
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
  
  values:
    replicas: 1
    minimumMasterNodes: 1
    esJavaOpts: "-Xmx512m -Xms512m" # 🟢 Lower memory usage to prevent RAM throttling
    resources:
      requests:
        cpu: "100m"      # 🟢 Scale down from 500m to 100m (0.1 CPU)
        memory: "1Gi"    # 🟢 Scale down from 2Gi to 1Gi
      limits:
        cpu: "500m"      # Allow it to burst up to 0.5 CPU if free
        memory: "1Gi"
    persistence:
      enabled: true
    volumeClaimTemplate:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 50Gi

    # 🟢 EMBEDDED INGRESS ROUTING CONFIGURATION
    ingress:
      enabled: true
      className: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      path: /
      hosts:
        - elasticsearch.forbzyltd.com
      tls:
        - secretName: elasticsearch-tls
          hosts:
            - elasticsearch.forbzyltd.com
